### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by meyerhoferc** [meyerhoferc/secret-santa#1]
Users can manage their profile. I imagine a profile should include info on user record (first_name, last_name, email, password) plus a photo, their preferences for gifts (wish list, clothes and shoe sizes, color preferences etc.).

Users should only be able to edit their own profle.

**Comment by kmeyerhofer** [comment]
On branch `user-profile`, a user can view their own profile (only displays first name, last name and email). We still need an edit page and a group public wish list area

**Comment by kmeyerhofer** [comment]
When changing a password, require the current password too.
