### ISSUE TITLE
Secret Santa

### ISSUE THREAD

**Issue by meyerhoferc** [meyerhoferc/secret-santa#5]
Users can see who they are a 'santa' for but not any other 'santa' assignments.

**Comment by meyerhoferc** [comment]
- Group owner clicks a button to assign santas once they know everyone has an account.
- Displays on each user's dashboard their assigned santa for that group. Only that user can see this information.
- Be able to send a message to your secret santa about gift drop off. This could be entered in the wish list or elsewhere and be restricted to only the santa user. This could show up on the santa's dashboard.

**Comment by kmeyerhofer** [comment]
Requested feature:
## Exclusion Teams (Name not final)
A group owner can place a user in an **optional** exclusion team. When it is time to assign secret santas, exclusion team members cannot be assigned to each other, but can be assigned to other users not in an exclusion team, or in a different exclusion team. A user can only be in one exclusion team per group and there can be many exclusion teams per group.

The primary purpose of this is to prevent santa assignments to immediate family members so matches can be made to more infrequently seen people.

### Implementation thoughts

#### Possible Issues
1. Too many users in exclusion teams that secret santa assignments couldn't be matched.
  * Possible solution:
    * Validation on the number of users in an exclusion team versus the total number of users, checked on secret santa assignment. The check on santa assignment would allow additions to the exclusion team when all users haven't joined the group.

2. TBD...
